// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCairMabuLTaQht1D8_sMGtdTsLoNpvvPI',
    appId: '1:818314108456:web:2e43a349160eb6d01f5f1d',
    messagingSenderId: '818314108456',
    projectId: 'video-conferencing-app-d0165',
    authDomain: 'video-conferencing-app-d0165.firebaseapp.com',
    storageBucket: 'video-conferencing-app-d0165.appspot.com',
    measurementId: 'G-DXTD1THC9Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBaH157nmL2afguXM3NbGLyq2Q7mJPQRRk',
    appId: '1:818314108456:android:4dc2032ec0a775831f5f1d',
    messagingSenderId: '818314108456',
    projectId: 'video-conferencing-app-d0165',
    storageBucket: 'video-conferencing-app-d0165.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYhKgSkBIVzaqVC-ji3-oVrenGOkRU9i0',
    appId: '1:818314108456:ios:01e36b2f14b47d4c1f5f1d',
    messagingSenderId: '818314108456',
    projectId: 'video-conferencing-app-d0165',
    storageBucket: 'video-conferencing-app-d0165.appspot.com',
    androidClientId: '818314108456-3cos071tcpqhlophnko5a3ap9brqk18j.apps.googleusercontent.com',
    iosClientId: '818314108456-ems6bg0vtsjp7kpu3h5lghmqf39e2jd3.apps.googleusercontent.com',
    iosBundleId: 'com.example.videoConferenceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCYhKgSkBIVzaqVC-ji3-oVrenGOkRU9i0',
    appId: '1:818314108456:ios:01e36b2f14b47d4c1f5f1d',
    messagingSenderId: '818314108456',
    projectId: 'video-conferencing-app-d0165',
    storageBucket: 'video-conferencing-app-d0165.appspot.com',
    androidClientId: '818314108456-3cos071tcpqhlophnko5a3ap9brqk18j.apps.googleusercontent.com',
    iosClientId: '818314108456-ems6bg0vtsjp7kpu3h5lghmqf39e2jd3.apps.googleusercontent.com',
    iosBundleId: 'com.example.videoConferenceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCairMabuLTaQht1D8_sMGtdTsLoNpvvPI',
    appId: '1:818314108456:web:d0d3b26d08502eb11f5f1d',
    messagingSenderId: '818314108456',
    projectId: 'video-conferencing-app-d0165',
    authDomain: 'video-conferencing-app-d0165.firebaseapp.com',
    storageBucket: 'video-conferencing-app-d0165.appspot.com',
    measurementId: 'G-86MM3BNDHX',
  );

}